### ISSUE TITLE
Unable to use Kubelogin with service principal login flow

### ISSUE THREAD

**Issue by shigupt202** [Azure/kubelogin#21]
Hi! I'm trying to use the Service principal login flow to login to my AAD enabled connected cluster to enable non interactive login for [Azure/aks-set-context](https://github.com/azure/aks-set-context/) action. However, I've been getting this error:
```
server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server has asked for the client to provide credentials",
  "reason": "Unauthorized",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "Security token validation failed."
      }
    ]
  },
  "code": 401
}]
```
Kubelogin works fine with interactive flow, but doesn't seem to work with service principals. 
Also, I could not find any executables in the latest release. So, I used the makefile in the source code to get kubelogin.exe. Could that be a reason for this issue? Or is there anything that I am missing?

**Comment by weinong** [comment]
@shigupt202 have we discussed offline? Service Principal login support is determined in the backend. Since the current graph API call to get /getMemberGroups doesn't support Service Principal, the only way to support SPN is to configure Guard to skip Graph API call when there is no overage claim (e.g. your SP is in less than 250 AAD groups)

https://github.com/appscode/guard/blob/master/docs/guides/authenticator/azure.md#skip-graph-api-call-when-overage-indicator-is-not-present

**Comment by shigupt202** [comment]
@weinong I don't think we have. But, thanks for the clarification. I tried this by passing `--azure.graph-call-on-overage-claim=true` while configuring guard on my api server and it worked!
