### ISSUE TITLE
Inject groups:scr1 objects through graph api call in JWT

### ISSUE THREAD

**Issue by djtje12** [Azure/kubelogin#76]
Hi, we are currently using kubelogin to authenticate against Azure AD and then use the JWT groups claim to authenticate against an EKS cluster in AWS.

Currently we have no Assignment required restrictions on the enterprise application, this way everyone from our organization can get a valid JWT token by using kubelogin. We do this because this saves us quite the administrative hassle of adding additional new groups to that enterprise application before they can sign in. We only check if a user is part of our domain and has valid credentials and some conditional access policies.

With that valid token you are able to use kubectl and when you know the cluster_ca and the cluster_url you are allowed to do calls to the kubernetes api. On the cluster itself we then have clusterrolebindings & rolebindings to further delegate permissions with regular kubernetes RBAC based of the objectid of a (A)AD group that needs to have permissions on the clusterresource(s).

For some of our users we have the well known [200 groups limit in the JWT token issue](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims). Based of that I've got the following question, is it possible to bypass this by having kubelogin directly query the graph url that's in the JWT and inject the groupid's in the JWT? [groups:src1](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims)

This in itself doesn't seem like a complex function to add in kubelogin but maybe there is some hidden complexitity that I don't know of.

**Comment by wiceywkus** [comment]
kubelogin cannot modify the JWT.  The tokens are digitally signed by Azure.  Changing it will break the checksum and the validation.

**Comment by weinong** [comment]
As much as I like the proposal, kubelogin is just a recipient of the AAD token and there is no way we can modify that. There are other projects such as https://github.com/kubeguard/guard that can address this limitation. If you need help in that regard, let me know. Otherwise, closing this issue for now

**Comment by saiharshitach** [comment]
@weinong is there any other solution which can decode the token which has more than 200 groups.. We are using kube-oidc-proxy plugin on EKS  which seems to be now maintained by Tremolo..They think this has to be done at kubelogin level and we also donot want to change too many configs in our existing clusters(huge footprint)looks like many of the users are hitting similar issue. Is there a solution where we can fix this from azure side in any way?

**Comment by wiceywkus** [comment]
Groups > 200.  It's an Azure issue.  But limiting the number of groups to 200 in an Access Token or an ID Token actually seems rather reasonable. (to me anyway, where I suffer from the same issue) 
You would have to change the EKS OIDC Provider configuration, but you could do something where you configure 'roles' for your AzureAD (or similar) App Registration and have it add 'roles' as a claim to the tokens.  Then have the EKS Identity Provider use 'roles' rather than 'groups' as the "Groups" claim.
You could do something similar with any custom claim.

**Comment by weinong** [comment]
I'd recommend configuring [app roles](https://learn.microsoft.com/en-us/entra/identity-platform/howto-add-app-roles-in-apps) and configure k8s to use `roles` claim instead of using `groups`.

**Comment by saiharshitach** [comment]
I know its too much to ask here but do we have any documentations on what all needs to be set up from azure side and approle side and what has to goin kubernetes rbac to get this working ?
Would that be the approle ID in RBAC ? or user ID ? Its a bit confusing for freshers like me in AZure portal 

@wiceywkus  @weinong
